all:	rocks hello life colors image

rocks: 
	tools/build.macOS rocks

hello: 
	tools/build.macOS hello

life: 
	tools/build.macOS life

colors: 
	tools/build.macOS colors

image: 
	tools/build.macOS image

clean:
	cd rust/weekit; cargo clean
	cd rust/svg; cargo clean
	rm -rf lib *.app
