#!/bin/sh

all:	app

libwee.so:	src/platform_pi.c src/touches_pi.c
	clang src/platform_pi.c src/touches_pi.c \
		-g \
		-I /opt/vc/include \
		-I /usr/local/include \
		-L /usr/local/lib \
		-I src \
		-lobjc \
		-shared -fpic \
		-ljpeg \
		-o libwee.so

app:	libwee.so
	# Build and install the main (Rust) binary.
	cd rust; cargo build

clean:
	cd rust; cargo clean
	rm -rf libwee.so
