AMANITHVG = third-party/amanithvg-sdk

CFLAGS = -c \
       	-g \
       	-I platform/macOS \
       	-I ${AMANITHVG}/include \
       	-I /usr/local/include \
       	-I src 

_OBJ = platform.o image.o term.o
OBJ = $(patsubst %,$(OUT_DIR)/%,$(_OBJ))

LIB = $(OUT_DIR)/libplatform.a

$(LIB): $(OBJ)
	ar crus $(LIB) $(OBJ)

$(OUT_DIR)/%.o:	platform/macOS/%.m
	clang $< $(CFLAGS) -o $@

$(OUT_DIR)/%.o:	platform/common/%.c
	clang $< $(CFLAGS) -o $@

clean:
	rm -f $(OBJ) $(LIB)
