

CFLAGS = \
	-c \
	-g \
	-I /opt/vc/include \
	-I /usr/local/include \
	-I src

_OBJ = input.o egl.o image.o term.o
OBJ = $(patsubst %,$(OUT_DIR)/%,$(_OBJ))

LIB = $(OUT_DIR)/libplatform.a

$(LIB): $(OBJ)
	ar crus $(LIB) $(OBJ)

$(OUT_DIR)/%.o:	platform/pi/%.c
	clang $< $(CFLAGS) -o $@

$(OUT_DIR)/%.o:	platform/common/%.c
	clang $< $(CFLAGS) -o $@

clean:
	rm -f $(LIB) $(OBJ)
